import {
  Apartment as VenueIcon,
} from '@mui/icons-material';

export const INITIAL_BANQUET_EVENTS = [
  {
    id: 'BEO-401',
    title: 'Vance & Sterling Royal Wedding Gala',
    client: 'Baroness Evelyn Vance • Vance Family Trust',
    venue: 'Grand Crystal Ballroom',
    status: 'Confirmed & Deposit Paid',
    statusType: 'confirmed',
    schedule: 'Oct 28, 2026 (18:00 – 23:30)',
    attendance: '320 Guests (Round Table Banquet (10-top))',
    catering: '6-Course Michelin Gala Dinner & Vintage Champagne Toast',
    totalPrice: '$68,500',
    depositPaid: '$35,000',
    avSetup: 'Full Line Array Audio, 4K LED Backdrop & Stage Spotlight',
    coordinator: 'Marcella Dubois (Senior Event Director)',
  },
  {
    id: 'BEO-402',
    title: 'Global Private Wealth & Tech Summit 2026',
    client: 'Julian Thorne • Thorne Capital Partners',
    venue: 'Grand Crystal Ballroom',
    status: 'BEO In Preparation',
    statusType: 'in-prep',
    schedule: 'Nov 04, 2026 (08:30 – 17:00)',
    attendance: '380 Guests (Theater Keynote & Stage)',
    catering: 'Executive All-Day Coffee Bar & Gourmet Buffet Luncheon',
    totalPrice: '$42,000',
    depositPaid: '$20,000',
    avSetup: 'Dual Projectors, Live Webcast Rig & 8 Wireless Lapel Mics',
    coordinator: 'Jonathan Sterling (Conference Lead)',
  },
  {
    id: 'BEO-403',
    title: 'Haute Horlogerie Luxury Watch Showcase',
    client: 'Genevieve Moreau • Vacheron & Patek Guild',
    venue: 'Skyline Rooftop Pavilion',
    status: 'In-Progress Live Event',
    statusType: 'in-progress',
    schedule: 'Today (19:00 – 23:00)',
    attendance: '140 Guests (Cocktail Reception Standing)',
    catering: 'Beluga Caviar Tasting, Truffle Canapés & Sommelier Wine Pairing',
    totalPrice: '$29,800',
    depositPaid: '$29,800',
    avSetup: 'Ambient DJ Sound System & Museum-Grade Vitrine Lighting',
    coordinator: 'Elena Rostova (VIP Hospitality)',
  },
  {
    id: 'BEO-404',
    title: 'Diplomatic Corps Autumn Ambassadorial Dinner',
    client: 'Ambassador Henri Zhao • Consular Diplomatic Mission',
    venue: 'Royal Executive Boardroom',
    status: 'Confirmed & Deposit Paid',
    statusType: 'confirmed',
    schedule: 'Oct 30, 2026 (19:30 – 22:30)',
    attendance: '28 Guests (U-Shape Executive)',
    catering: 'Private Chef 5-Course State Banquet with Wine Pairing',
    totalPrice: '$12,400',
    depositPaid: '$12,400',
    avSetup: 'Encrypted Video Teleconference & Interpretation Booths',
    coordinator: 'Marcella Dubois (Senior Event Director)',
  },
  {
    id: 'BEO-405',
    title: 'Luminis Biotech European Board Meeting',
    client: 'Dr. Aris Thorne • Luminis Therapeutics',
    venue: 'Botanical Garden Terrace',
    status: 'BEO In Preparation',
    statusType: 'in-prep',
    schedule: 'Nov 12, 2026 (11:00 – 16:00)',
    attendance: '160 Guests (Classroom & Workshop)',
    catering: 'Farm-to-Table Organic Garden Lunch & Artisan Gelato Bar',
    totalPrice: '$24,800',
    depositPaid: '$10,000',
    avSetup: 'High-Brightness Laser Displays & Polycom Hybrid Audio',
    coordinator: 'Jonathan Sterling (Conference Lead)',
  },
];

export const VENUE_FILTERS = [
  { id: 'all', label: 'All Venues', icon: VenueIcon },
  { id: 'grand-crystal', label: 'Grand Crystal Ballroom', pax: '450 Pax' },
  { id: 'skyline-rooftop', label: 'Skyline Rooftop Pavilion', pax: '180 Pax' },
  { id: 'royal-executive', label: 'Royal Executive Boardroom', pax: '35 Pax' },
  { id: 'botanical-garden', label: 'Botanical Garden Terrace', pax: '220 Pax' },
];

export const STATUS_FILTERS = [
  'All Statuses',
  'Confirmed & Deposit Paid',
  'BEO In Preparation',
  'In-Progress Live Event',
  'Completed & Invoiced',
];
